{'author': 'witxka@gmail.com',
 'description': 'webups plugin for check_mk 2',
 'download_url': 'http://example.com/webups/',
 'files': {'agent_based': ['webups.py'],
           'agents': ['plugins/webups'],
           'alert_handlers': [],
           'bin': [],
           'checkman': [],
           'checks': [],
           'doc': [],
           'inventory': [],
           'lib': [],
           'locales': [],
           'mibs': [],
           'notifications': [],
           'pnp-templates': [],
           'web': []},
 'name': 'webups',
 'title': ' webups plugin for check_mk 2',
 'version': '2.1',
 'version.min_required': '2.0.0p1',
 'version.packaged': '2.0.0p5',
 'version.usable_until': None}
